method: random  # Use random for broad exploration, bayes later
metric:
  name: val_loss
  goal: minimize

parameters:
  model:
    value: LSTM

  loss:
    values: ["RMSE", "MAE"] 

  hidden_size:
    values: [64, 128, 192]

  dropout:
    min: 0.05
    max: 0.2
    distribution: uniform

  weight_decay:
    min: 1e-6
    max: 1e-4
    distribution: log_uniform_values

  learning_rate:
    min: 1e-5
    max: 5e-4
    distribution: log_uniform_values

  epochs:
    value: 50


command: ["python", "train.py"]