method: random
metric:
  name: val_loss
  goal: minimize

parameters:
  model:
    value: TemporalFusionTransformer

  loss:
    value: QuantileLoss

  quantiles:
    value: [0.2, 0.5, 0.8]

  hidden_size:
    value: 96  # Expand down to test smaller models

  hidden_continuous_size:
    value: 8

  attention_head_size:
    value: 4

  dropout:
    value: 0.16742

  learning_rate:
    value: 0.00012508

  weight_decay:
    value: 0.00002399

  epochs:
    value: 50

command: ["python", "train.py"]